/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/calculator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Perform a calculation
         * @description Performs a calculation based on the provided numbers and operation.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 5 */
                        number1: number;
                        /** @example 3 */
                        number2: number;
                        /** @example + */
                        operation: string;
                    };
                };
            };
            responses: {
                /** @description Calculation result */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example + */
                            operation?: string;
                            /** @example 5 */
                            number1?: number;
                            /** @example 3 */
                            number2?: number;
                            /** @example 8 */
                            result?: number;
                            /**
                             * Format: date-time
                             * @example 2023-10-01T12:00:00Z
                             */
                            timestamp?: string;
                            /** @example 100 */
                            responseTime?: number;
                        };
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Invalid operator */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
